CREATE LOGIN Util1
	WITH PASSWORD = 'pwd',
	DEFAULT_DATABASE = [master],
	CHECK_EXPIRATION = OFF,
	CHECK_POLICY = OFF

CREATE LOGIN Util2
	WITH PASSWORD = 'pwd',
	DEFAULT_DATABASE = [Papyrus],
	CHECK_EXPIRATION = OFF,
	CHECK_POLICY = OFF

CREATE LOGIN Util3
	WITH PASSWORD = 'pwd',
	DEFAULT_DATABASE = [Papyrus],
	CHECK_EXPIRATION = OFF,
	CHECK_POLICY = off

USE Papyrus
go

CREATE USER Util1 FOR LOGIN Util1
CREATE USER Util2 FOR LOGIN Util2
CREATE USER Util3 FOR LOGIN Util3
GO

GRANT INSERT ON entcom TO Util1
GRANT INSERT ON fournis TO Util1
GRANT INSERT ON ligcom TO Util1
GRANT INSERT ON produit TO Util1
GRANT INSERT ON vente TO Util1

GRANT SELECT ON entcom TO Util1
GRANT SELECT ON fournis TO Util1
GRANT SELECT ON ligcom TO Util1
GRANT SELECT ON produit TO Util1
GRANT SELECT ON vente TO Util1

DENY DELETE ON entcom TO Util1
DENY DELETE ON fournis TO Util1
DENY DELETE ON ligcom TO Util1
DENY DELETE ON produit TO Util1
DENY DELETE ON vente TO Util1
GO

GRANT SELECT ON fournis TO public
GO

CREATE ROLE gestion
GO

GRANT SELECT ON fournis TO gestion
GRANT UPDATE ON fournis TO gestion
GO

EXECUTE sp_addrolemember 'gestion','Util3'

